### ISSUE TITLE
[Bug]: No error given when storage volume is zero or negative

### ISSUE THREAD

**Issue by KelbijStarDeltares** [Project-OMOTES/user_feedback#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

Not possible to run, because storage volume was not specified by the user. Even though the user had run the ESDl validator,, which was ok.

### Steps to reproduce the problem

1. Make network with storage
2. Do not fill in a volume
3. Run optimization routine.

### What should have happened?

Should be detected by the ESDL validator.
Ideally, the user get a clear error when running.

### What browsers do you use to access the UI?

None

**Comment by FJanssen-TNO** [comment]
@jimrojerTNO  It checks whether a volume (m3) or capacity (J) is available otherwise it gives an error.
There was a bug in the validator, so it should be solved now.

@KelbijStarDeltares can you please confirm if it works for your esdl?
