### ISSUE TITLE
[Bug]: Storage is incorrectly not removed and buffers don't seem to have volume even when connected

### ISSUE THREAD

**Issue by RonaldBerk** [Project-OMOTES/user_feedback#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

The optimizer removes pipes to the buffer, but doesn't remove the buffer and does not calculate the volume

### Steps to reproduce the problem

1. Load ESDL
2. Duplicate ESDL
3. Run Grow optimizer (buffers are optional)
4. Jim will attach the EDSL
5. 

### What should have happened?

Buffers which are connected should have volume and buffers which aren't connected should be removed

### What browsers do you use to access the UI?

Microsoft Edge

**Comment by jimrojerTNO** [comment]
[Pijnacker-Nootdorp - 2023-10-05T164845.981.txt](https://github.com/Project-OMOTES/user_feedback/files/13513820/Pijnacker-Nootdorp.-.2023-10-05T164845.981.txt)

**Comment by KelbijStarDeltares** [comment]
Same in this case. Network with optional storage. Optimizer places storage but not the pipes from the storage to the network. Results finished without error.

Steps to reproduce the problem
Open model in map editor

Run optimizer routine

Check results
[val_simple with storage two demand profiles.esdl.txt](https://github.com/Project-OMOTES/user_feedback/files/14652418/val_simple.with.storage.two.demand.profiles.esdl.txt)
![image](https://github.com/Project-OMOTES/user_feedback/assets/100276887/d6f0aa7b-04a5-41b3-bfed-5ddabfcf284b)

**Comment by FJanssen-TNO** [comment]
The results writing of the optimizer to the ESDL has been improved over time, together with some more recent bugs this has been fixed, the upcoming release will the contain the latest improvements.
