### ISSUE TITLE
[Feature Request]: Import GIS files of existing heat networks 

### ISSUE THREAD

**Issue by jvandorstrhdhv** [Project-OMOTES/user_feedback#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would your feature do ?

From the presentation of TPG it became clear that in version 0.1 it will become possible to export files from the toolkit to GIS software. It would be useful if it is also possible to import GIS files in a user friendly way, because existing heating networks in use cases are often available in this format. This way existing networks do not have to be drawn again.

### Proposed workflow

1. Start new project
2. Load in existing GIS file
3. Assign diameters to imported network if this is not possible to include in the importation

**Comment by edwinmat** [comment]
In the WarmingUp project we've spent quite some time discussing this with people from Capturam, Vattenfal and Rotterdam Engineering. A lot of GIS files (shapefiles in this case) we had as examples, contained double line pieces (so exactly overlapping) or non connected line pieces (or almost connected). 

This repository was created: https://github.com/EnergyTransition/shapefile-2-esdl

It contains code to parse a shapefile and make it into an ESDL file. At this moment, there is some tweaking required with parameters/tolerances in the code. So you need some Python skills. But it definitely can be used. Please let me know your thoughts.

**Comment by ewoudwerkman** [comment]
Next to the project @edwinmat mentions, the MapEditor contains functionality to import shapefiles: 
![image](https://github.com/Project-OMOTES/user_feedback/assets/2264267/764cae15-ac82-4022-b586-efa02196faf1)

Exporting to shapefiles can be found under the File menu:
![image](https://github.com/Project-OMOTES/user_feedback/assets/2264267/998ed1cf-33f0-4c78-8fec-89cf20452664)

But as Edwin mentions: other GIS format have limited capabilities to store connectivity information which is required for the optimizations in OMOTES, so expect some postprocessing that is necessary to create a valid ESDL for an optimization/simulation.

**Comment by edwinmatthijssen** [comment]
These 2 functionalities have a very "bare minimum implementation" and have not yet been properly tested. One of the possible issues is properly handling larger shapefiles (I'm pretty sure that there is a limit, but don't know where yet)

What I would like to do some day, is to extend this "import/export shapefile" functionality to let the user select what data in the shapefile to map on what ESDL attributes
