### ISSUE TITLE
[Bug]: Part of the menu ribbon not available on smaller resolution screens

### ISSUE THREAD

**Issue by JurrianVRHDHV** [Project-OMOTES/user_feedback#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

When using the ESDL Map Editor on a smaller resolution or with a partial browser window, the [File, Edit, Services, View & Help] menu options dissapear once the window is made too narrow.
The EDR assets button and 3 others selection sliders remain even on the smallest possible width.

### Steps to reproduce the problem

1. Open the ESDL Map Editor
2. Take the browser window out of full screen mode

A. Reduce the horizontal width of the browser window
B. Reduce the screen resolution 
C. Open the program on a smaller screen (width)

Full width
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/c95d6173-92d7-4280-a2a4-07df08622cdb)
2/3 screen
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/ee556f5b-2e83-4cd9-96c4-7ec9f9594561)
1/2 screen
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/163ceaa5-aaf8-4e9a-8b87-5a997f1d0c01)
smallest width
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/7d1ce91a-46c0-4e5e-87f9-2347e24c0f83)

### What should have happened?

The Menu ribbon (including menu options, EDR assets button and 3 seletion sliders should either:
1. Fully remain (becoming stacked)
2. Prioritize the menu options over the EDR assts and 3 selection sliders

### What browsers do you use to access the UI?

Mozilla Firefox

### Additional information

Minor issue, but does impact accessibility of the program on older/lower resolution screens.
And in my case I prefer to work with multiple windows on the same screen.

**Comment by ewoudwerkman** [comment]
With a too small window, the menu (File, Edit, ...) itself was not visible anymore and could not be opened. This is fixed in the next release (24.6) such that you are still able to see the menu (hamburger) and use it. 

There is still an issue with the readability, but it does work now. To completely fix the cluttering of the other buttons, we need to redesign that part of the GUI, but that does not have priority on our roadmap currently.
