### ISSUE TITLE
[Bug]: Asset polygons remain in ESDL file when reloading.

### ISSUE THREAD

**Issue by JurrianVRHDHV** [Project-OMOTES/user_feedback#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

During the drawing of a network, I used the draw asset as a polygon tool to create various clusters.
Whilst drawing I made various mistakes (wrong shape, location, asset type) and tried to delete both the asset point and polygon layers.
The toolkit lets me delete the polygon and point layers visually. After which I use the draw asset to draw a new (corrected) polygon.
When reloading the file the deletion is undone, causing an overlap of old and new polygons and points.

Example of resulting overlapping layers due to incorrect removal
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/e2849a42-8129-4c10-ba00-c0b667011535)

This happens regardless of saving and reloading or restarting the browser/PC/map editor/using a different browser)

### Steps to reproduce the problem

1. Open ESDL map editor
2. Unzip and open file [ESDL_DenHaag_V2.3.47_ERRORFILE.esdl] in the map editor
[ESDL_DenHaag_V2.3.47_ERRORFILE.zip](https://github.com/Project-OMOTES/user_feedback/files/14356608/ESDL_DenHaag_V2.3.47_ERRORFILE.zip)
3. Select 'Delete Layers' in toolbar
4. Delete (one of the) various incorrect (visible as overlapping) polygons
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/fe3064db-20f1-4b92-95d2-13fc1fcc7d29)
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/16655ecb-4da4-455e-abfb-b6c28632fc40)
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/9096f910-35ef-458b-bbb7-23f7cb5d3efa)
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/e0307e62-1716-4d3a-ba54-aa19287f59f2)

5. Check 'Save' on the 'Delete Layers' tooloption
6. Save ESDL-file to local system
7.  Optionally: remove the EnergySystem from the top right ESDL layers
8. Close map editor/browser (and restart PC)

9. Open new ESDL map editor
10. Load the saved ESDL file
11. Check if point and polygon layers have been correctly removed.

### What should have happened?

The various deleted polygon- and point layers should remain deleted after saving and reloading the ESDL file.

### What browsers do you use to access the UI?

Mozilla Firefox

**Comment by ewoudwerkman** [comment]
Also nice catch!
Deleting of a polygon of an asset was only done in the frontend, nothing happened in the backend. This is now fixed by adding a deletion event to the polygon of this asset.
Fixed in next MapEditor release (24.6)
