### ISSUE TITLE
[Bug]: (NWN Toolkit Geosmartdesign) - illogical way of sorting available assets

### ISSUE THREAD

**Issue by MaPet01** [Project-OMOTES/user_feedback#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

Not really a bug, but an improvement for the NWN Toolkit Geosmartdesign. 

When you draw for example an _ESDL - Transport line_, you have to select an asset. A pop-up box with possible assets is shown. The possible assets have an illogical way of sorting. Therefor it takes time to find the right asset.

Also the available Producer assets are not sorted right.

![image](https://github.com/Project-OMOTES/user_feedback/assets/147378837/94e5d66a-6bbe-4f2c-98d3-d162bd87c6d8)

### Steps to reproduce the problem

Draw (for example) an _ESDL - Transport line_, 
A pop-up box with possible assets is shown. 
The possible assets have an illogical way of sorting.

### What should have happened?

I would recommend to sort the pipeline assets as:
Steel-S1-DN20
Steel-S1-DN32
Steel-S1-DN40
......
Steel-S2-DN20
Steel-S2-DN32
........
Steel-S3-DN20
Steel-S3-DN32

### What browsers do you use to access the UI?

None

**Comment by TPG-JonPosthuma** [comment]
@samvanderzwan  Opgelost in de nieuwe release, dit ter info.
