### ISSUE TITLE
[Bug]: Polygon has flow direction indicators

### ISSUE THREAD

**Issue by JurrianVRHDHV** [Project-OMOTES/user_feedback#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

Hovering over or selecting a polygon layers of which the asset point has been connected to a supply pipeline shows a flow direction.

![Screenshot (32)](https://github.com/Project-OMOTES/user_feedback/assets/152510091/ee2b0679-3f6c-4faf-863a-cc0c80fcf3f7)

Whilst this is logical for a

### Steps to reproduce the problem

1. Open ESDL Map Editor
2. Select asset type [used generic consumer]
3. Draw a new area/asset as a polygon using the draw polygon tool.
4. Finish drawing the polygon
5. Select 'pipe' in the topbar menu and use the draw "a cable or a pipe" toolkit option to draw a pipe connected to the input of the polygon asset.
6. Finish drawing the line
7. Go to the Edit topbar menu and select 'Energy carriers'
8. Select Heat commodity, fill in the name [Test], Supply temp. [70] and return temp. [40] and click add.
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/173f0ea3-883f-464f-8ebe-473084f541c2)

10. Rightclick on the line to open the options menu and select 'Set Carrier'.
11. Select the added [Test] Carrier.
12. The [now default red collored polygon should show directional arrows on the outline.
![afbeelding](https://github.com/Project-OMOTES/user_feedback/assets/152510091/4abd0edb-7ffe-4a4b-8229-58bc29aeed0a)

### What should have happened?

The asset polygon should match the color of the set carrier (including outline and infil), but its outline should not have directional arrows

### What browsers do you use to access the UI?

Mozilla Firefox

### Additional information

After testing a bit with Sam, we found that the color change and directional arrows are set to the input carrier and not dependent on other connected carriers.

**Comment by edwinmatthijssen** [comment]
Interesting bug....           assets "as polygons" has not been used extensively before, so multiple bugs might be still present

**Comment by ewoudwerkman** [comment]
Issue existed because in Leaflet polygons are subclasses of polylines, so the MapEditor applied the styles of the carrier to it (including arrows) similar to lines (pipes/cables). This has now been resolved, as these polygons should not change color (areas do not have a carrier), but keep the color they have (usually green for assets)
Fixed in next release (24.6)
