### ISSUE TITLE
[Bug]: Not possible to set correct carries on connecting lines

### ISSUE THREAD

**Issue by KelbijStarDeltares** [Project-OMOTES/user_feedback#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

Trying to connect all components in the mapeditor. Keep having issue with the carries on connection lines. For example I either have no carrier on a connection line or the wrong one. 

### Steps to reproduce the problem

1. Load the ESDL
2. Connect all components.
3. Check with the validator.
4. Another check: Save the esdl and reopen the esdl.

### What should have happened?

Connection lines from the return pipe to assests should have the return carrier and the other way around for the supply pipe.
[test_simple storage_error.esdl.txt](https://github.com/Project-OMOTES/user_feedback/files/14648550/test_simple.storage_error.esdl.txt)

### What browsers do you use to access the UI?

None

**Comment by FJanssen-TNO** [comment]
If I understand correctly this is the cause and solution, however when I run the validator it does already give me error for not connecting ports properly or wrong assignment of carriers:

The Residualheatsource has its own ports connected to each other, its own inport connected to its own outport. This causes the same carrier being parsed through the entire network. 
This connection should be remove, the following steps can be taken:
-click ResidualHeatSource_1
- unfold Ports, unfold both OutPort and InPort
- delete the REsdiualHeatSource_1 from the ConnectedTo of both ports.
After this, the assignment of carriers can be done again and no error with respect to this should arise.

**Comment by KelbijStarDeltares** [comment]
Thank you Femke for checking. I will try it according to your steps. 
It seems to be caused while/after running the dual pipe service.

**Comment by KelbijStarDeltares** [comment]
Still the same issue:
![image](https://github.com/Project-OMOTES/user_feedback/assets/100276887/e6e71dde-30e5-40ba-aa19-80b9e3bf3604)
![image](https://github.com/Project-OMOTES/user_feedback/assets/100276887/977d7a6a-4a61-4411-909a-94b402804437)

**Comment by KelbijStarDeltares** [comment]
[test_simple storage error 2.esdl.txt](https://github.com/Project-OMOTES/user_feedback/files/14649072/test_simple.storage.error.2.esdl.txt)

**Comment by FJanssen-TNO** [comment]
A return temperature is required for the return carrier like this:
![image](https://github.com/Project-OMOTES/user_feedback/assets/137757789/fd1b03bf-03ee-4dd9-bf11-4bf5dde5ad39)

I suppose we could give a more descriptive return error.

**Comment by FJanssen-TNO** [comment]
Here both above errors have been solved.
[test_simple with return network with return network.esdl.txt](https://github.com/Project-OMOTES/user_feedback/files/14649080/test_simple.with.return.network.with.return.network.esdl.txt)

**Comment by KelbijStarDeltares** [comment]
That was it! 
Indeed the error can be more descriptive, but also maybe a non-zero default value for the return carrier when using the dual pipe service or make the user fill in a value. Or other solutions that make it more clear for the user.
