### ISSUE TITLE
[Bug]: Heat direction of pipes might be wrong - Results log

### ISSUE THREAD

**Issue by jvandorstrhdhv** [Project-OMOTES/user_feedback#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

After running a succesfull heat network optimization calculation, the log of the result shows: "Heat directions of pipes might be wrong. Check Pipe10_ret." for all return pipes. I don't know what the effect of this is on the actual results. 

### Steps to reproduce the problem

1. Run the attached esdl file and look in the log. Calculation did take +-4 hours (with only 30 heating demands)
2. Look in the results log 

[DH_Jan_V1 with return network_GrowOptimized.txt](https://github.com/Project-OMOTES/user_feedback/files/14945394/DH_Jan_V1.with.return.network_GrowOptimized.txt)

### What should have happened?

Should not show up in the log if there is nothing wrong, or it should clearly indicate that the results cannot be trusted and where the problem does occur. 

### What browsers do you use to access the UI?

Google Chrome

**Comment by KobusVanRooyen** [comment]
This is will be reviewed to make it more clear what this means

**Comment by KobusVanRooyen** [comment]
@samvanderzwan this write out to the terminal was due to legacy code. The message "Heat direction of pipes might be wrong" will appear in the log anymore as it has been removed. Please close this issue. Can we close issues? Or do you want to close issues like this once it has been resolved?
