### ISSUE TITLE
[Bug]: Overlapping nametags of assets

### ISSUE THREAD

**Issue by JurrianVRHDHV** [Project-OMOTES/user_feedback#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What happened?

Hovering over an asset shows 2 different "nametags", which overlap (see image). This would not be an issue, be it that the bottom tag also contains information (and a shortcut) to the heating profile menu.

![Untitled](https://github.com/Project-OMOTES/user_feedback/assets/152510091/b34abca1-448f-4dc3-afc3-8cd8ba8583c7)

It happened on both Firefox and Chrome and seems to be linked to this specific ESDL file.
When loading another ESDL file or creating a brand new network, it does not happen.

[Base Netwerk Delft_V2.1.zip](https://github.com/Project-OMOTES/user_feedback/files/14945709/Base.Netwerk.Delft_V2.1.zip)

### Steps to reproduce the problem

1. Load ESDL file "Base Network Delft_V2.1"
2. Hover over any asset point
3. This should show 2 nametags at the same time

### What should have happened?

Only 1 nametag with the heat profile shortcut should be showing.

### What browsers do you use to access the UI?

Mozilla Firefox

**Comment by ewoudwerkman** [comment]
Fixed in MapEditor release 24.2.2 (or in 24.4.0) which is deployed for MVP.
