### ISSUE TITLE
[Feature Request]: nPro workflow and features

### ISSUE THREAD

**Issue by MirkaKukurugyova** [Project-OMOTES/user_feedback#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would your feature do ?

-	The workflow in nPro is relevant for Toolkit UI development
-       Please have a look at the nPro software: (https://app.npro.energy/energy-hub)
-       For example the scenario comparison is very useful idea (total cost vs. CO2 emissions). 
-       Also P&ID -> energy hub, size technologies feature, ....

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

### Additional information

no

**Comment by samvanderzwan** [comment]
Thanks for this info. Maybe good to have a session with @WouterSpaak and @edwinmatthijssen to show which features you like in nPRO.

**Comment by MirkaKukurugyova** [comment]
Ok, no problem.
I plan to come next week to Delft.

Have a nice day.

Mirka

**Comment by samvanderzwan** [comment]
@rdrijvers something to get inspiration from, but enatuurlijk is no longer part of the project

**Comment by edwinmatthijssen** [comment]
The link still results in the same error, so it's very difficult to get the inspiration :-(

**Comment by samvanderzwan** [comment]
This works better: https://app.npro.energy/en

**Comment by edwinmatthijssen** [comment]
Ah! I remember this tool. The question back then was “what specific parts do you like?”; not sure if we got an answer. Isn’t there a related issue in the WarmingUp project’s issue list?

**Comment by samvanderzwan** [comment]
There is no related issue in WarmingUp.
My guess is that the GUI is much simpler, no map only schematic representation of the assets, which is a totally different approach then we are doing in NWN. Ennatuurlijk is stopping as partner, so we are going to close this issue,
